export default {
  "m_dirt" : [
    {"page":"fe","categoryId":"move","name":"","param":"Infantry","imgSrc":"{A01_IMG}4/45/Icon_Move_Infantry.png"},
    {"page":"fe","categoryId":"move","name":"","param":"Armored","imgSrc":"{A01_IMG}8/80/Icon_Move_Armored.png"},
    {"page":"fe","categoryId":"move","name":"","param":"Cavalry","imgSrc":"{A01_IMG}9/9f/Icon_Move_Cavalry.png"},
    {"page":"fe","categoryId":"move","name":"","param":"Flying","imgSrc":"{A01_IMG}7/73/Icon_Move_Flying.png"},
    {"page":"fe","categoryId":"weapon","name":"","param":"Axe","imgSrc":"{A01_IMG}6/6e/Icon_Class_Green_Axe.png"},
    {"page":"fe","categoryId":"weapon","name":"","param":"Blue Beast","imgSrc":"{A01_IMG}3/30/Icon_Class_Blue_Beast.png"},
    {"page":"fe","categoryId":"weapon","name":"","param":"Blue Breath","imgSrc":"{A01_IMG}3/3d/Icon_Class_Blue_Breath.png"},
    {"page":"fe","categoryId":"weapon","name":"","param":"Blue Dagger","imgSrc":"{A01_IMG}8/81/Icon_Class_Blue_Dagger.png"},
    {"page":"fe","categoryId":"weapon","name":"","param":"Blue Tome","imgSrc":"{A01_IMG}8/8e/Icon_Class_Blue_Tome.png"},
    {"page":"fe","categoryId":"weapon","name":"","param":"Blue bow","imgSrc":"{A01_IMG}1/1e/Icon_Class_Blue_Bow.png"},
    {"page":"fe","categoryId":"weapon","name":"","param":"Colorless Beast","imgSrc":"{A01_IMG}0/02/Icon_Class_Colorless_Beast.png"},
    {"page":"fe","categoryId":"weapon","name":"","param":"Colorless Breath","imgSrc":"{A01_IMG}d/d7/Icon_Class_Colorless_Breath.png"},
    {"page":"fe","categoryId":"weapon","name":"","param":"Colorless Dagger","imgSrc":"{A01_IMG}6/68/Icon_Class_Colorless_Dagger.png"},
    {"page":"fe","categoryId":"weapon","name":"","param":"Colorless Tome","imgSrc":"{A01_IMG}3/39/Icon_Class_Colorless_Tome.png"},
    {"page":"fe","categoryId":"weapon","name":"","param":"Colorless bow","imgSrc":"{A01_IMG}c/c1/Icon_Class_Colorless_Bow.png"},
    {"page":"fe","categoryId":"weapon","name":"","param":"Green Beast","imgSrc":"{A01_IMG}d/d7/Icon_Class_Green_Beast.png"},
    {"page":"fe","categoryId":"weapon","name":"","param":"Green Breath","imgSrc":"{A01_IMG}e/eb/Icon_Class_Green_Breath.png"},
    {"page":"fe","categoryId":"weapon","name":"","param":"Green Dagger","imgSrc":"{A01_IMG}9/9d/Icon_Class_Green_Dagger.png"},
    {"page":"fe","categoryId":"weapon","name":"","param":"Green Tome","imgSrc":"{A01_IMG}7/75/Icon_Class_Green_Tome.png"},
    {"page":"fe","categoryId":"weapon","name":"","param":"Green bow","imgSrc":"{A01_IMG}7/76/Icon_Class_Green_Bow.png"},
    {"page":"fe","categoryId":"weapon","name":"","param":"Lance","imgSrc":"{A01_IMG}6/60/Icon_Class_Blue_Lance.png"},
    {"page":"fe","categoryId":"weapon","name":"","param":"Red Beast","imgSrc":"{A01_IMG}2/2f/Icon_Class_Red_Beast.png"},
    {"page":"fe","categoryId":"weapon","name":"","param":"Red Breath","imgSrc":"{A01_IMG}e/ee/Icon_Class_Red_Breath.png"},
    {"page":"fe","categoryId":"weapon","name":"","param":"Red Dagger","imgSrc":"{A01_IMG}a/a0/Icon_Class_Red_Dagger.png"},
    {"page":"fe","categoryId":"weapon","name":"","param":"Red Tome","imgSrc":"{A01_IMG}8/8a/Icon_Class_Red_Tome.png"},
    {"page":"fe","categoryId":"weapon","name":"","param":"Red bow","imgSrc":"{A01_IMG}2/25/Icon_Class_Red_Bow.png"},
    {"page":"fe","categoryId":"weapon","name":"","param":"Staff","imgSrc":"{A01_IMG}c/cd/Icon_Class_Colorless_Staff.png"},
    {"page":"fe","categoryId":"weapon","name":"","param":"Sword","imgSrc":"{A01_IMG}4/47/Icon_Class_Red_Sword.png"},
    {"page":"fe","categoryId":"color","name":"","param":"Red","name":"","imgSrc":"https://img.game8.co/2632302/ed1436fb5084e2dee1ecc2c4d9583f56.png/show"},
    {"page":"fe","categoryId":"color","name":"","param":"Blue","name":"","imgSrc":"https://img.game8.co/2632299/942b111dacf4c81eae08da25b1d05895.png/show"},
    {"page":"fe","categoryId":"color","name":"","param":"Green","name":"","imgSrc":"https://img.game8.co/2632301/dd4ad50a52b0c355a8b2b7b225e34a65.png/show"},
    {"page":"fe","categoryId":"color","name":"","param":"Colorless","name":"","imgSrc":"https://img.game8.co/2632300/a37e5d656e036aaecef2e361be714443.png/show"},
    {"page":"fe","categoryId":"entry","name":"","param":"Heroes","imgSrc":"{A01_IMG}d/d5/Icon_MiniUnit_Head_0.png"},
    {"page":"fe","categoryId":"entry","name":"","param":"Shadow Dragon","imgSrc":"{A01_IMG}1/12/Icon_MiniUnit_Head_1.png"},
    {"page":"fe","categoryId":"entry","name":"","param":"Echoes","imgSrc":"{A01_IMG}a/a2/Icon_MiniUnit_Head_2.png"},
    {"page":"fe","categoryId":"entry","name":"","param":"Genealogy of the Holy War","imgSrc":"{A01_IMG}6/6e/Icon_MiniUnit_Head_3.png"},
    {"page":"fe","categoryId":"entry","name":"","param":"Radiant Dawn","imgSrc":"{A01_IMG}7/78/Icon_MiniUnit_Head_9.png"},
    {"page":"fe","categoryId":"entry","name":"","param":"The Sacred Stones","imgSrc":"{A01_IMG}5/57/Icon_MiniUnit_Head_7.png"},
    {"page":"fe","categoryId":"entry","name":"","param":"Fates","imgSrc":"{A01_IMG}e/e9/Icon_MiniUnit_Head_11.png"},
    {"page":"fe","categoryId":"entry","name":"","param":"Awakening","imgSrc":"{A01_IMG}f/ff/Icon_MiniUnit_Head_10.png"},
    {"page":"fe","categoryId":"entry","name":"","param":"Thracia 776","imgSrc":"{A01_IMG}1/12/Icon_MiniUnit_Head_4.png"},
    {"page":"fe","categoryId":"entry","name":"","param":"Path of Radiance","imgSrc":"{A01_IMG}8/80/Icon_MiniUnit_Head_8.png"},
    {"page":"fe","categoryId":"entry","name":"","param":"The Binding Blade","imgSrc":"{A01_IMG}c/c8/Icon_MiniUnit_Head_5.png"},
    {"page":"fe","categoryId":"entry","name":"","param":"The Blazing Blade","imgSrc":"{A01_IMG}d/d8/Icon_MiniUnit_Head_6.png"},
    {"page":"fe","categoryId":"entry","name":"","param":"Three Houses","imgSrc":"{A01_IMG}a/a9/Icon_MiniUnit_Head_12.png"},
    {"page":"fe","categoryId":"entry","name":"","param":"Tokyo Mirage Sessions ♯FE Encore","imgSrc":"{A01_IMG}0/0c/Icon_MiniUnit_Head_13.png"},
    {"page":"fe","categoryId":"entry","name":"","param":"Engage","imgSrc":"{A01_IMG}3/33/Icon_MiniUnit_Head_14.png"},
    {"page":"azurlane","categoryId":"rarity","param":"Elite","name":"精锐","imgSrc":""},
    {"page":"azurlane","categoryId":"rarity","param":"Super Rare","name":"超稀有","imgSrc":""},
    {"page":"azurlane","categoryId":"rarity","param":"Ultra Rare","name":"海上传奇","imgSrc":""},
    {"page":"azurlane","categoryId":"rarity","param":"Rare","name":"稀有","imgSrc":""},
    {"page":"azurlane","categoryId":"rarity","param":"Normal","name":"普通","imgSrc":""},
    {"page":"azurlane","categoryId":"classification","param":"Destroyer","name":"驱逐舰","imgSrc":""},
    {"page":"azurlane","categoryId":"classification","param":"Light Cruiser","name":"轻巡洋舰","imgSrc":""},
    {"page":"azurlane","categoryId":"classification","param":"Battleship","name":"战列舰","imgSrc":""},
    {"page":"azurlane","categoryId":"classification","param":"Light Aircraft Carrier","name":"轻航母","imgSrc":""},
    {"page":"azurlane","categoryId":"classification","param":"Aircraft Carrier","name":"航空母舰","imgSrc":""},
    {"page":"azurlane","categoryId":"classification","param":"Repair Ship","name":"维修","imgSrc":""},
    {"page":"azurlane","categoryId":"classification","param":"Battlecruiser","name":"战列巡洋舰","imgSrc":""},
    {"page":"azurlane","categoryId":"classification","param":"Monitor","name":"监视舰","imgSrc":""},
    {"page":"azurlane","categoryId":"classification","param":"Submarine","name":"潜艇","imgSrc":""},
    {"page":"azurlane","categoryId":"classification","param":"Submarine Carrier","name":"潜母","imgSrc":""},
    {"page":"azurlane","categoryId":"classification","param":"Munition Ship","name":"军火船","imgSrc":""},
    {"page":"azurlane","categoryId":"classification","param":"Large Cruiser","name":"大型巡洋舰","imgSrc":""},
    {"page":"azurlane","categoryId":"classification","param":"Sailing Frigate (Submarine)","name":"护卫舰","imgSrc":""},
    {"page":"azurlane","categoryId":"classification","param":"Sailing Frigate (Vanguard)","name":"护卫潜艇","imgSrc":""},
    {"page":"azurlane","categoryId":"classification","param":"Sailing Frigate (Main)","name":"主护卫舰","imgSrc":""},
    {"page":"azurlane","categoryId":"faction","param":"Eagle Union","name":"白鹰","imgSrc":"{A04_IMG}1/17/Us_1.png"},
    {"page":"azurlane","categoryId":"faction","param":"Royal Navy","name":"皇家海军","imgSrc":"{A04_IMG}9/99/En_1.png"},
    {"page":"azurlane","categoryId":"faction","param":"Sakura Empire","name":"重樱","imgSrc":"{A04_IMG}e/e5/Jp_1.png"},
    {"page":"azurlane","categoryId":"faction","param":"Iron Blood","name":"铁血","imgSrc":"{A04_IMG}0/04/De_1.png"},
    {"page":"azurlane","categoryId":"faction","param":"Dragon Empery","name":"东煌","imgSrc":"{A04_IMG}2/26/Cn_1.png"},
    {"page":"azurlane","categoryId":"faction","param":"Northern Parliament","name":"北方联合","imgSrc":"{A04_IMG}0/0d/Sn_1.png"},
    {"page":"azurlane","categoryId":"faction","param":"Iris Libre","name":"自由","imgSrc":"{A04_IMG}7/78/Ff_1.png"},
    {"page":"azurlane","categoryId":"faction","param":"Vichya Dominion","name":"维系教廷","imgSrc":"{A04_IMG}a/a1/Vf_1.png"},
    {"page":"azurlane","categoryId":"faction","param":"Sardegna Empire","name":"撒丁帝国","imgSrc":"{A04_IMG}f/f1/Rn_1.png"},
    {"page":"azurlane","categoryId":"faction","param":"META","name":"META","imgSrc":"{A04_IMG}e/e6/Meta_1.png"},
    {"page":"azurlane","categoryId":"faction","param":"Tempesta","name":"飓风","imgSrc":"{A04_IMG}f/fa/Mot_1.png"},
    {"page":"azurlane","categoryId":"faction","param":"Venus Vacation","name":"死或生沙滩排球","imgSrc":"{A04_IMG}0/0d/Um_1.png"},
    {"page":"fgo","categoryId":"classType","param":"Saber","name":"Saber","imgSrc":"{A02_IMG}2/20/Class-Saber-Gold.webp"},
    {"page":"fgo","categoryId":"classType","param":"Archer","name":"Archer","imgSrc":"{A02_IMG}4/42/Class-Archer-Gold.webp"},
    {"page":"fgo","categoryId":"classType","param":"Lancer","name":"Lancer","imgSrc":"{A02_IMG}6/6a/Class-Lancer-Gold.webp"},
    {"page":"fgo","categoryId":"classType","param":"Rider","name":"Rider","imgSrc":"{A02_IMG}1/16/Class-Rider-Gold.webp"},
    {"page":"fgo","categoryId":"classType","param":"Caster","name":"Caster","imgSrc":"{A02_IMG}2/2a/Class-Caster-Gold.webp"},
    {"page":"fgo","categoryId":"classType","param":"Assassin","name":"Assassin","imgSrc":"{A02_IMG}6/64/Class-Assassin-Gold.webp"},
    {"page":"fgo","categoryId":"classType","param":"Berserker","name":"Berserker","imgSrc":"{A02_IMG}e/e2/Class-Berserker-Gold.webp"},
    {"page":"fgo","categoryId":"classType","param":"Ruler","name":"Ruler","imgSrc":"{A02_IMG}2/21/Class-Ruler-Gold.webp"},
    {"page":"fgo","categoryId":"classType","param":"Avenger","name":"Avenger","imgSrc":"{A02_IMG}c/c7/Class-Avenger-Gold.webp"},
    {"page":"fgo","categoryId":"classType","param":"Foreigner","name":"Foreigner","imgSrc":"{A02_IMG}e/e5/Class-Foreigner-Gold.webp"},
    {"page":"fgo","categoryId":"classType","param":"Pretender","name":"Pretender","imgSrc":"{A02_IMG}2/28/Class-Pretender-Gold.webp"},
    {"page":"fgo","categoryId":"classType","param":"MoonCancer","name":"MoonCancer","imgSrc":"{A02_IMG}6/65/Class-MoonCancer-Gold.webp"},
    {"page":"fgo","categoryId":"classType","param":"Alterego","name":"Alterego","imgSrc":"{A02_IMG}1/1b/Class-Alterego-Gold.webp"},
    {"page":"crazyones","categoryId":"heroine","param":"苏小野","name":"苏小野","imgSrc":""},
    {"page":"crazyones","categoryId":"heroine","param":"智子","name":"智子","imgSrc":""},
    {"page":"crazyones","categoryId":"heroine","param":"白鸥","name":"白鸥","imgSrc":""},
    {"page":"crazyones","categoryId":"heroine","param":"夏冰","name":"夏冰","imgSrc":""},
    {"page":"crazyones","categoryId":"heroine","param":"其他","name":"其他","imgSrc":""},
  ],
  "URL_MATCH" : {
    "{A01_IMG}" : "https://static.wikia.nocookie.net/feheroes_gamepedia_en/images/",
    "{A02_IMG}" : "https://static.wikia.nocookie.net/fategrandorder/images/",
    "{A04_IMG}" : "https://azurlane.netojuu.com/images/"
  }
}
